kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: amq
spec:
  kafka:
    version: 3.5.0
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          type: tls
        name: external
        port: 9094
        tls: true
        type: route
    authorization:
      type: simple
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: "3.5"
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    resources: 
      requests:
        memory: 2Gi
        cpu:  1
      limits:
        memory: 4Gi
        cpu: 2
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "INFO"
        log4j.logger.kafka: "INFO"
        log4j.logger.org.apache.kafka: "INFO"
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 10Gi
        type: persistent-claim
      - deleteClaim: false
        id: 1
        size: 10Gi
        type: persistent-claim
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    resources: 
      requests:
        memory: '1Gi'
        cpu:  '500m'
      limits:
        memory: '2Gi'
        cpu: 1
#
#    jvmOptions: 
#      -Xms: "1024"
#      -Xmx: "1024"
#
    storage:
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
