---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: comum
  labels:
    strimzi.io/cluster: amq
spec:
  partitions: 4
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: umaparticao
  labels:
    strimzi.io/cluster: amq
spec:
  partitions: 4
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824